-- Mock data for local development of DevAI Hub
-- All demo accounts use password: Demo@123
-- Safe to run repeatedly: previous records tagged @devai.local are replaced.

USE forum_db;
SET NAMES utf8mb4 COLLATE utf8mb4_unicode_ci;
START TRANSACTION;

-- Remove the previous mock dataset in foreign-key-safe order.
UPDATE posts
SET best_answer_comment_id = NULL
WHERE author_id IN (SELECT id FROM users WHERE email LIKE '%@devai.local');

DELETE FROM notifications
WHERE user_id IN (SELECT id FROM users WHERE email LIKE '%@devai.local')
   OR actor_id IN (SELECT id FROM users WHERE email LIKE '%@devai.local')
   OR post_id IN (
       SELECT id FROM posts
       WHERE author_id IN (SELECT id FROM users WHERE email LIKE '%@devai.local')
   );

DELETE FROM reports
WHERE reporter_id IN (SELECT id FROM users WHERE email LIKE '%@devai.local')
   OR handled_by IN (SELECT id FROM users WHERE email LIKE '%@devai.local')
   OR post_id IN (
       SELECT id FROM posts
       WHERE author_id IN (SELECT id FROM users WHERE email LIKE '%@devai.local')
   );

DELETE FROM moderation_logs
WHERE moderator_id IN (SELECT id FROM users WHERE email LIKE '%@devai.local')
   OR target_user_id IN (SELECT id FROM users WHERE email LIKE '%@devai.local')
   OR post_id IN (
       SELECT id FROM posts
       WHERE author_id IN (SELECT id FROM users WHERE email LIKE '%@devai.local')
   );

DELETE FROM post_appeals
WHERE user_id IN (SELECT id FROM users WHERE email LIKE '%@devai.local')
   OR admin_id IN (SELECT id FROM users WHERE email LIKE '%@devai.local')
   OR post_id IN (
       SELECT id FROM posts
       WHERE author_id IN (SELECT id FROM users WHERE email LIKE '%@devai.local')
   );

DELETE FROM post_likes
WHERE user_id IN (SELECT id FROM users WHERE email LIKE '%@devai.local')
   OR post_id IN (
       SELECT id FROM posts
       WHERE author_id IN (SELECT id FROM users WHERE email LIKE '%@devai.local')
   );

DELETE FROM bookmarks
WHERE user_id IN (SELECT id FROM users WHERE email LIKE '%@devai.local')
   OR post_id IN (
       SELECT id FROM posts
       WHERE author_id IN (SELECT id FROM users WHERE email LIKE '%@devai.local')
   );

DELETE FROM comments
WHERE author_id IN (SELECT id FROM users WHERE email LIKE '%@devai.local')
   OR post_id IN (
       SELECT id FROM posts
       WHERE author_id IN (SELECT id FROM users WHERE email LIKE '%@devai.local')
   );

DELETE FROM posts
WHERE author_id IN (SELECT id FROM users WHERE email LIKE '%@devai.local');

DELETE FROM password_reset_tokens
WHERE user_id IN (SELECT id FROM users WHERE email LIKE '%@devai.local');

DELETE FROM users WHERE email LIKE '%@devai.local';

-- Password hash generated by password_hash('Demo@123', PASSWORD_BCRYPT).
SET @demo_password = '$2y$10$59xGonytzvwhSVHFQbKo4ufPmwpIpmqVkxJ1C5NU0ElkSC0eKxgb2';

INSERT INTO users (
    role_id, username, email, password_hash, display_name, bio,
    reputation, status, banned_reason, created_at
)
SELECT id, 'admin_devai', 'admin@devai.local', @demo_password,
       'Admin DevAI', 'Quản trị viên của diễn đàn DevAI Hub.', 1500,
       'active', NULL, CURRENT_TIMESTAMP - INTERVAL 120 DAY
FROM roles WHERE name = 'admin';

INSERT INTO users (
    role_id, username, email, password_hash, display_name, bio,
    reputation, status, banned_reason, created_at
)
SELECT id, 'mod_linh', 'mod.linh@devai.local', @demo_password,
       'Linh Moderator', 'Kiểm duyệt viên, yêu thích PHP và cơ sở dữ liệu.', 980,
       'active', NULL, CURRENT_TIMESTAMP - INTERVAL 100 DAY
FROM roles WHERE name = 'moderator';

INSERT INTO users (
    role_id, username, email, password_hash, display_name, bio,
    reputation, status, banned_reason, created_at
)
SELECT id, 'an_nguyen', 'an.nguyen@devai.local', @demo_password,
       'An Nguyễn', 'Sinh viên đang học PHP, MySQL và lập trình web.', 320,
       'active', NULL, CURRENT_TIMESTAMP - INTERVAL 70 DAY
FROM roles WHERE name = 'member';

INSERT INTO users (
    role_id, username, email, password_hash, display_name, bio,
    reputation, status, banned_reason, created_at
)
SELECT id, 'minh_tran', 'minh.tran@devai.local', @demo_password,
       'Minh Trần', 'Backend developer, quan tâm API và bảo mật.', 540,
       'active', NULL, CURRENT_TIMESTAMP - INTERVAL 65 DAY
FROM roles WHERE name = 'member';

INSERT INTO users (
    role_id, username, email, password_hash, display_name, bio,
    reputation, status, banned_reason, created_at
)
SELECT id, 'hai_le', 'hai.le@devai.local', @demo_password,
       'Hải Lê', 'Tìm hiểu Machine Learning và Computer Vision.', 410,
       'active', NULL, CURRENT_TIMESTAMP - INTERVAL 55 DAY
FROM roles WHERE name = 'member';

INSERT INTO users (
    role_id, username, email, password_hash, display_name, bio,
    reputation, status, banned_reason, created_at
)
SELECT id, 'thuy_linh', 'thuy.linh@devai.local', @demo_password,
       'Thùy Linh', 'Yêu thích NLP, LLM và Prompt Engineering.', 470,
       'active', NULL, CURRENT_TIMESTAMP - INTERVAL 48 DAY
FROM roles WHERE name = 'member';

INSERT INTO users (
    role_id, username, email, password_hash, display_name, bio,
    reputation, status, banned_reason, created_at
)
SELECT id, 'quang_phuc', 'quang.phuc@devai.local', @demo_password,
       'Quang Phúc', 'Frontend developer sử dụng JavaScript và Bootstrap.', 245,
       'active', NULL, CURRENT_TIMESTAMP - INTERVAL 35 DAY
FROM roles WHERE name = 'member';

INSERT INTO users (
    role_id, username, email, password_hash, display_name, bio,
    reputation, status, banned_reason, created_at
)
SELECT id, 'lan_anh', 'lan.anh@devai.local', @demo_password,
       'Lan Anh', 'Sinh viên tìm kiếm tài nguyên học tập và cơ hội thực tập.', 185,
       'active', NULL, CURRENT_TIMESTAMP - INTERVAL 25 DAY
FROM roles WHERE name = 'member';

INSERT INTO users (
    role_id, username, email, password_hash, display_name, bio,
    reputation, status, banned_reason, banned_until, created_at
)
SELECT id, 'spammer_demo', 'spammer@devai.local', @demo_password,
       'Tài khoản vi phạm', 'Tài khoản mẫu dùng để kiểm thử trang quản trị.', -20,
       'banned', 'Đăng nội dung quảng cáo lặp lại', CURRENT_TIMESTAMP + INTERVAL 30 DAY,
       CURRENT_TIMESTAMP - INTERVAL 20 DAY
FROM roles WHERE name = 'member';

-- Resolve identifiers used by the remainder of the mock data.
SELECT id INTO @admin_id FROM users WHERE username = 'admin_devai';
SELECT id INTO @mod_id FROM users WHERE username = 'mod_linh';
SELECT id INTO @an_id FROM users WHERE username = 'an_nguyen';
SELECT id INTO @minh_id FROM users WHERE username = 'minh_tran';
SELECT id INTO @hai_id FROM users WHERE username = 'hai_le';
SELECT id INTO @linh_id FROM users WHERE username = 'thuy_linh';
SELECT id INTO @phuc_id FROM users WHERE username = 'quang_phuc';
SELECT id INTO @lan_id FROM users WHERE username = 'lan_anh';
SELECT id INTO @spammer_id FROM users WHERE username = 'spammer_demo';

SELECT id INTO @cat_basic FROM categories WHERE slug = 'hoc-tap-lap-trinh-co-ban';
SELECT id INTO @cat_ai FROM categories WHERE slug = 'ai-khoa-hoc-du-lieu';
SELECT id INTO @cat_qa FROM categories WHERE slug = 'hoi-dap-do-an-go-loi';
SELECT id INTO @cat_resource FROM categories WHERE slug = 'tai-nguyen-co-hoi-nghe-nghiep';

-- Posts span all four categories and all major post types.
INSERT INTO posts (
    author_id, category_id, title, slug, content_html, post_type,
    status, is_pinned, is_locked, view_count, created_at
) VALUES
(@an_id, @cat_qa,
 'Lỗi kết nối MySQL bằng PHP PDO trên XAMPP',
 'loi-ket-noi-mysql-php-pdo-xampp',
 '<p>Mình gặp lỗi <strong>Connection refused</strong> khi kết nối PDO tới MySQL. Apache chạy bình thường nhưng ứng dụng không truy cập được database.</p><pre><code>$pdo = new PDO("mysql:host=127.0.0.1;dbname=forum_db", "root", "");</code></pre>',
 'question', 'published', 0, 0, 286, CURRENT_TIMESTAMP - INTERVAL 12 DAY),

(@linh_id, @cat_ai,
 'So sánh Gemini API và OpenAI API cho chatbot tiếng Việt',
 'so-sanh-gemini-api-openai-api-chatbot-tieng-viet',
 '<p>Mình tổng hợp một số khác biệt về chi phí, độ trễ, context window và khả năng xử lý tiếng Việt khi xây dựng chatbot hỗ trợ sinh viên.</p>',
 'discussion', 'published', 1, 0, 742, CURRENT_TIMESTAMP - INTERVAL 10 DAY),

(@hai_id, @cat_ai,
 'Lộ trình học Machine Learning cho người mới bắt đầu',
 'lo-trinh-hoc-machine-learning-nguoi-moi',
 '<p>Lộ trình đề xuất gồm Python, NumPy, Pandas, xác suất thống kê, scikit-learn và một dự án cuối khóa.</p>',
 'resource', 'published', 1, 0, 618, CURRENT_TIMESTAMP - INTERVAL 9 DAY),

(@hai_id, @cat_qa,
 'Mô hình nhận diện ảnh bị overfitting phải xử lý thế nào?',
 'mo-hinh-nhan-dien-anh-bi-overfitting',
 '<p>Training accuracy đạt 98% nhưng validation accuracy chỉ đạt 72%. Mình đang dùng một CNN nhỏ và khoảng 3.000 ảnh huấn luyện.</p>',
 'question', 'published', 0, 0, 433, CURRENT_TIMESTAMP - INTERVAL 8 DAY),

(@lan_id, @cat_resource,
 'Tổng hợp nguồn học AI miễn phí cho sinh viên',
 'tong-hop-nguon-hoc-ai-mien-phi',
 '<p>Danh sách khóa học và tài liệu nhập môn Machine Learning, Deep Learning, NLP và Computer Vision có thể học miễn phí.</p>',
 'resource', 'published', 0, 0, 351, CURRENT_TIMESTAMP - INTERVAL 7 DAY),

(@minh_id, @cat_qa,
 'Cách tối ưu truy vấn danh sách bài viết có nhiều lượt thích',
 'toi-uu-truy-van-bai-viet-nhieu-luot-thich',
 '<p>Mình cần sắp xếp feed theo số lượt thích và số bình luận. Nên dùng subquery, JOIN hay lưu sẵn bộ đếm?</p>',
 'question', 'published', 0, 0, 297, CURRENT_TIMESTAMP - INTERVAL 6 DAY),

(@linh_id, @cat_ai,
 '5 nguyên tắc viết prompt rõ ràng cho trợ lý AI',
 'nam-nguyen-tac-viet-prompt-ro-rang',
 '<p>Prompt tốt nên có mục tiêu, ngữ cảnh, dữ liệu đầu vào, ràng buộc và định dạng kết quả mong muốn.</p>',
 'discussion', 'published', 0, 0, 505, CURRENT_TIMESTAMP - INTERVAL 5 DAY),

(@phuc_id, @cat_qa,
 'Fetch API trả về JSON nhưng giao diện không cập nhật',
 'fetch-api-json-giao-dien-khong-cap-nhat',
 '<p>Request trả HTTP 200 và dữ liệu đúng trong Network tab, nhưng danh sách bài viết vẫn không render lại.</p><pre><code>fetch(url).then(r =&gt; r.json()).then(renderPosts);</code></pre>',
 'question', 'published', 0, 0, 214, CURRENT_TIMESTAMP - INTERVAL 4 DAY),

(@mod_id, @cat_basic,
 'Hướng dẫn cấu trúc PHP MVC thuần cho đồ án XAMPP',
 'huong-dan-php-mvc-thuan-xampp',
 '<p>Bài viết trình bày luồng request qua public/index.php, Router, Controller, Model và View; đồng thời sử dụng PDO prepared statements.</p>',
 'resource', 'published', 1, 0, 890, CURRENT_TIMESTAMP - INTERVAL 3 DAY),

(@lan_id, @cat_resource,
 'Chia sẻ kinh nghiệm chuẩn bị CV xin thực tập AI',
 'kinh-nghiem-chuan-bi-cv-thuc-tap-ai',
 '<p>CV nên làm nổi bật dự án có mã nguồn, dữ liệu, cách đánh giá mô hình và kết quả định lượng thay vì chỉ liệt kê khóa học.</p>',
 'job', 'published', 0, 0, 176, CURRENT_TIMESTAMP - INTERVAL 2 DAY),

(@an_id, @cat_basic,
 'Các lỗi thường gặp khi import database bằng phpMyAdmin',
 'loi-thuong-gap-import-database-phpmyadmin',
 '<p>Một số lỗi phổ biến gồm sai collation, file SQL quá lớn, trùng khóa ngoại và import sai thứ tự bảng.</p>',
 'discussion', 'published', 0, 0, 129, CURRENT_TIMESTAMP - INTERVAL 1 DAY),

(@minh_id, @cat_ai,
 'Bản nháp: thử nghiệm RAG cho tài liệu nội bộ',
 'ban-nhap-thu-nghiem-rag-tai-lieu-noi-bo',
 '<p>Nội dung bản nháp chưa công khai.</p>',
 'discussion', 'draft', 0, 0, 0, CURRENT_TIMESTAMP),

(@phuc_id, @cat_basic,
 'Chia sẻ template CV cho lập trình viên mới ra trường',
 'chia-se-template-cv-lap-trinh-vien-moi-ra-truong',
 '<p>Mình chia sẻ một số mẫu CV kèm liên kết tải về, hy vọng giúp ích cho các bạn mới ra trường.</p>',
 'resource', 'hidden', 0, 0, 54, CURRENT_TIMESTAMP - INTERVAL 4 DAY),

(@lan_id, @cat_resource,
 'Tổng hợp link tải slide bài giảng AI học kỳ này',
 'tong-hop-link-tai-slide-bai-giang-ai-hoc-ky-nay',
 '<p>Mình tổng hợp lại các link slide bài giảng để mọi người tiện ôn tập.</p>',
 'resource', 'hidden', 0, 0, 88, CURRENT_TIMESTAMP - INTERVAL 6 DAY);

UPDATE posts SET hidden_reason = 'Bài viết chứa liên kết tải xuống chưa được kiểm chứng, có nguy cơ vi phạm bản quyền.'
WHERE slug = 'chia-se-template-cv-lap-trinh-vien-moi-ra-truong';
UPDATE posts SET hidden_reason = 'Nội dung trùng lặp với tài nguyên đã được BQT ghim trước đó.'
WHERE slug = 'tong-hop-link-tai-slide-bai-giang-ai-hoc-ky-nay';

SELECT id INTO @p1 FROM posts WHERE slug = 'loi-ket-noi-mysql-php-pdo-xampp';
SELECT id INTO @p2 FROM posts WHERE slug = 'so-sanh-gemini-api-openai-api-chatbot-tieng-viet';
SELECT id INTO @p3 FROM posts WHERE slug = 'lo-trinh-hoc-machine-learning-nguoi-moi';
SELECT id INTO @p4 FROM posts WHERE slug = 'mo-hinh-nhan-dien-anh-bi-overfitting';
SELECT id INTO @p5 FROM posts WHERE slug = 'tong-hop-nguon-hoc-ai-mien-phi';
SELECT id INTO @p6 FROM posts WHERE slug = 'toi-uu-truy-van-bai-viet-nhieu-luot-thich';
SELECT id INTO @p7 FROM posts WHERE slug = 'nam-nguyen-tac-viet-prompt-ro-rang';
SELECT id INTO @p8 FROM posts WHERE slug = 'fetch-api-json-giao-dien-khong-cap-nhat';
SELECT id INTO @p9 FROM posts WHERE slug = 'huong-dan-php-mvc-thuan-xampp';
SELECT id INTO @p10 FROM posts WHERE slug = 'kinh-nghiem-chuan-bi-cv-thuc-tap-ai';
SELECT id INTO @p11 FROM posts WHERE slug = 'loi-thuong-gap-import-database-phpmyadmin';
SELECT id INTO @p_hidden1 FROM posts WHERE slug = 'chia-se-template-cv-lap-trinh-vien-moi-ra-truong';
SELECT id INTO @p_hidden2 FROM posts WHERE slug = 'tong-hop-link-tai-slide-bai-giang-ai-hoc-ky-nay';

-- Technology tags.
INSERT INTO post_tags (post_id, tag_id)
SELECT @p1, id FROM tags WHERE slug IN ('php', 'mysql', 'xampp');
INSERT INTO post_tags (post_id, tag_id)
SELECT @p2, id FROM tags WHERE slug IN ('openai-api', 'gemini-api', 'nlp');
INSERT INTO post_tags (post_id, tag_id)
SELECT @p3, id FROM tags WHERE slug IN ('python', 'machine-learning');
INSERT INTO post_tags (post_id, tag_id)
SELECT @p4, id FROM tags WHERE slug IN ('python', 'machine-learning', 'computer-vision');
INSERT INTO post_tags (post_id, tag_id)
SELECT @p5, id FROM tags WHERE slug IN ('machine-learning', 'nlp', 'computer-vision');
INSERT INTO post_tags (post_id, tag_id)
SELECT @p6, id FROM tags WHERE slug IN ('mysql', 'php');
INSERT INTO post_tags (post_id, tag_id)
SELECT @p7, id FROM tags WHERE slug IN ('prompt-engineering', 'openai-api', 'gemini-api');
INSERT INTO post_tags (post_id, tag_id)
SELECT @p8, id FROM tags WHERE slug IN ('javascript', 'html-css');
INSERT INTO post_tags (post_id, tag_id)
SELECT @p9, id FROM tags WHERE slug IN ('php', 'mysql', 'xampp');
INSERT INTO post_tags (post_id, tag_id)
SELECT @p10, id FROM tags WHERE slug IN ('machine-learning', 'python');
INSERT INTO post_tags (post_id, tag_id)
SELECT @p11, id FROM tags WHERE slug IN ('mysql', 'xampp');

-- Comments and nested replies.
INSERT INTO comments (post_id, author_id, parent_id, content_html, created_at) VALUES
(@p1, @minh_id, NULL, '<p>Kiểm tra MySQL đã chạy và cổng trong file cấu hình có đúng 3306 không. Với XAMPP, tài khoản mặc định thường là root và mật khẩu rỗng.</p>', CURRENT_TIMESTAMP - INTERVAL 11 DAY),
(@p1, @mod_id, NULL, '<p>Hãy bật extension <code>pdo_mysql</code>, dùng host 127.0.0.1 và thêm <code>charset=utf8mb4</code> vào DSN.</p>', CURRENT_TIMESTAMP - INTERVAL 11 DAY),
(@p2, @minh_id, NULL, '<p>Nên benchmark bằng cùng một bộ câu hỏi tiếng Việt thay vì chỉ so sánh cảm nhận.</p>', CURRENT_TIMESTAMP - INTERVAL 9 DAY),
(@p2, @lan_id, NULL, '<p>Phần chi phí rất hữu ích. Bạn có thể bổ sung giới hạn request mỗi phút không?</p>', CURRENT_TIMESTAMP - INTERVAL 8 DAY),
(@p3, @linh_id, NULL, '<p>Nên bổ sung bước học cách chia train, validation và test để tránh đánh giá sai mô hình.</p>', CURRENT_TIMESTAMP - INTERVAL 8 DAY),
(@p4, @linh_id, NULL, '<p>Thử data augmentation, dropout, weight decay và early stopping. Đồng thời kiểm tra tập validation có cùng phân phối với tập train không.</p>', CURRENT_TIMESTAMP - INTERVAL 7 DAY),
(@p4, @minh_id, NULL, '<p>Nếu dữ liệu ít, transfer learning thường hiệu quả hơn huấn luyện CNN từ đầu.</p>', CURRENT_TIMESTAMP - INTERVAL 7 DAY),
(@p5, @an_id, NULL, '<p>Cảm ơn bạn, danh sách này rất phù hợp cho người mới.</p>', CURRENT_TIMESTAMP - INTERVAL 6 DAY),
(@p6, @mod_id, NULL, '<p>Trước tiên hãy tạo index cho các cột JOIN và lọc. Chỉ nên lưu bộ đếm khi đã đo được truy vấn tổng hợp thực sự chậm.</p>', CURRENT_TIMESTAMP - INTERVAL 5 DAY),
(@p6, @hai_id, NULL, '<p>Bạn có thể dùng EXPLAIN để xem MySQL có sử dụng index không.</p>', CURRENT_TIMESTAMP - INTERVAL 5 DAY),
(@p7, @phuc_id, NULL, '<p>Mình thấy yêu cầu định dạng đầu ra giúp giảm đáng kể việc phải xử lý lại câu trả lời.</p>', CURRENT_TIMESTAMP - INTERVAL 4 DAY),
(@p8, @minh_id, NULL, '<p>Kiểm tra renderPosts có trả về HTML nhưng chưa gán vào DOM hay không. Mở Console để xem lỗi JavaScript.</p>', CURRENT_TIMESTAMP - INTERVAL 3 DAY),
(@p9, @an_id, NULL, '<p>Phần Router rất dễ hiểu. Có thể bổ sung ví dụ middleware xác thực không?</p>', CURRENT_TIMESTAMP - INTERVAL 2 DAY),
(@p9, @lan_id, NULL, '<p>Mình đã chạy được project bằng cấu trúc này trên XAMPP.</p>', CURRENT_TIMESTAMP - INTERVAL 2 DAY),
(@p10, @hai_id, NULL, '<p>Nên đặt link GitHub và demo trực tiếp ngay dưới phần mô tả dự án.</p>', CURRENT_TIMESTAMP - INTERVAL 1 DAY),
(@p11, @phuc_id, NULL, '<p>Nếu báo lỗi kích thước file, có thể chỉnh upload_max_filesize và post_max_size trong php.ini cho môi trường local.</p>', CURRENT_TIMESTAMP);

-- Add one nested reply.
SELECT id INTO @p1_first_comment
FROM comments WHERE post_id = @p1 ORDER BY id LIMIT 1;
INSERT INTO comments (post_id, author_id, parent_id, content_html, created_at)
VALUES (@p1, @an_id, @p1_first_comment, '<p>Đúng rồi, MySQL của mình chưa được bật. Cảm ơn bạn!</p>', CURRENT_TIMESTAMP - INTERVAL 10 DAY);

-- Best answers for solved questions.
SELECT id INTO @p1_best
FROM comments
WHERE post_id = @p1 AND author_id = @mod_id
ORDER BY id LIMIT 1;
UPDATE posts SET best_answer_comment_id = @p1_best WHERE id = @p1;

SELECT id INTO @p4_best
FROM comments
WHERE post_id = @p4 AND author_id = @linh_id
ORDER BY id LIMIT 1;
UPDATE posts SET best_answer_comment_id = @p4_best WHERE id = @p4;

SELECT id INTO @p6_best
FROM comments
WHERE post_id = @p6 AND author_id = @mod_id
ORDER BY id LIMIT 1;
UPDATE posts SET best_answer_comment_id = @p6_best WHERE id = @p6;

SELECT id INTO @p8_best
FROM comments
WHERE post_id = @p8 AND author_id = @minh_id
ORDER BY id LIMIT 1;
UPDATE posts SET best_answer_comment_id = @p8_best WHERE id = @p8;

-- Likes and bookmarks for feed ranking and profile pages.
INSERT INTO post_likes (user_id, post_id, created_at) VALUES
(@minh_id, @p1, CURRENT_TIMESTAMP - INTERVAL 10 DAY),
(@hai_id, @p1, CURRENT_TIMESTAMP - INTERVAL 9 DAY),
(@linh_id, @p1, CURRENT_TIMESTAMP - INTERVAL 8 DAY),
(@an_id, @p2, CURRENT_TIMESTAMP - INTERVAL 8 DAY),
(@minh_id, @p2, CURRENT_TIMESTAMP - INTERVAL 7 DAY),
(@hai_id, @p2, CURRENT_TIMESTAMP - INTERVAL 6 DAY),
(@lan_id, @p2, CURRENT_TIMESTAMP - INTERVAL 5 DAY),
(@phuc_id, @p2, CURRENT_TIMESTAMP - INTERVAL 4 DAY),
(@an_id, @p3, CURRENT_TIMESTAMP - INTERVAL 7 DAY),
(@linh_id, @p3, CURRENT_TIMESTAMP - INTERVAL 6 DAY),
(@lan_id, @p3, CURRENT_TIMESTAMP - INTERVAL 5 DAY),
(@minh_id, @p4, CURRENT_TIMESTAMP - INTERVAL 6 DAY),
(@an_id, @p5, CURRENT_TIMESTAMP - INTERVAL 5 DAY),
(@phuc_id, @p6, CURRENT_TIMESTAMP - INTERVAL 4 DAY),
(@lan_id, @p7, CURRENT_TIMESTAMP - INTERVAL 3 DAY),
(@an_id, @p9, CURRENT_TIMESTAMP - INTERVAL 2 DAY),
(@hai_id, @p9, CURRENT_TIMESTAMP - INTERVAL 1 DAY),
(@phuc_id, @p9, CURRENT_TIMESTAMP - INTERVAL 1 DAY),
(@linh_id, @p10, CURRENT_TIMESTAMP);

INSERT INTO bookmarks (user_id, post_id, created_at) VALUES
(@an_id, @p3, CURRENT_TIMESTAMP - INTERVAL 7 DAY),
(@an_id, @p9, CURRENT_TIMESTAMP - INTERVAL 2 DAY),
(@minh_id, @p2, CURRENT_TIMESTAMP - INTERVAL 6 DAY),
(@hai_id, @p5, CURRENT_TIMESTAMP - INTERVAL 5 DAY),
(@linh_id, @p3, CURRENT_TIMESTAMP - INTERVAL 5 DAY),
(@phuc_id, @p7, CURRENT_TIMESTAMP - INTERVAL 3 DAY),
(@lan_id, @p9, CURRENT_TIMESTAMP - INTERVAL 1 DAY),
(@lan_id, @p10, CURRENT_TIMESTAMP);

-- Notifications: read and unread examples.
INSERT INTO notifications (
    user_id, actor_id, post_id, comment_id, type, message, is_read, read_at, created_at
) VALUES
(@an_id, @mod_id, @p1, @p1_best, 'comment', 'Linh Moderator đã trả lời câu hỏi của bạn.', 1, CURRENT_TIMESTAMP - INTERVAL 10 DAY, CURRENT_TIMESTAMP - INTERVAL 11 DAY),
(@mod_id, @an_id, @p1, @p1_best, 'best_answer', 'Câu trả lời của bạn đã được chọn là câu trả lời hay nhất.', 1, CURRENT_TIMESTAMP - INTERVAL 9 DAY, CURRENT_TIMESTAMP - INTERVAL 10 DAY),
(@linh_id, @phuc_id, @p7, NULL, 'like', 'Quang Phúc đã thích bài viết của bạn.', 0, NULL, CURRENT_TIMESTAMP - INTERVAL 2 DAY),
(@mod_id, @lan_id, @p9, NULL, 'comment', 'Lan Anh đã bình luận về bài viết của bạn.', 0, NULL, CURRENT_TIMESTAMP - INTERVAL 1 DAY),
(@lan_id, @hai_id, @p10, NULL, 'comment', 'Hải Lê đã bình luận về bài viết của bạn.', 0, NULL, CURRENT_TIMESTAMP),
(@phuc_id, @mod_id, @p_hidden1, NULL, 'moderation', 'Bài viết "Chia sẻ template CV cho lập trình viên mới ra trường" của bạn đã bị Moderator hủy. Lý do: Bài viết chứa liên kết tải xuống chưa được kiểm chứng, có nguy cơ vi phạm bản quyền.', 0, NULL, CURRENT_TIMESTAMP - INTERVAL 4 DAY),
(@lan_id, @admin_id, @p_hidden2, NULL, 'moderation', 'Bài viết "Tổng hợp link tải slide bài giảng AI học kỳ này" của bạn đã bị Moderator hủy. Lý do: Nội dung trùng lặp với tài nguyên đã được BQT ghim trước đó.', 1, CURRENT_TIMESTAMP - INTERVAL 5 DAY, CURRENT_TIMESTAMP - INTERVAL 6 DAY),
(@lan_id, @admin_id, @p_hidden2, NULL, 'moderation', 'Kháng cáo cho bài viết "Tổng hợp link tải slide bài giảng AI học kỳ này" đã bị từ chối. Lý do: Nội dung vẫn trùng lặp phần lớn với tài nguyên đã ghim, cần bổ sung góc nhìn riêng trước khi đăng lại.', 0, NULL, CURRENT_TIMESTAMP - INTERVAL 2 DAY);

-- Post appeals: one still pending review, one already rejected by admin.
INSERT INTO post_appeals (post_id, user_id, reason, status, admin_id, admin_reason, created_at, handled_at) VALUES
(@p_hidden1, @phuc_id,
 'Các liên kết mình chia sẻ đều là tài liệu do chính mình biên soạn, không vi phạm bản quyền. Mong BQT xem xét lại.',
 'pending', NULL, NULL, CURRENT_TIMESTAMP - INTERVAL 1 DAY, NULL),
(@p_hidden2, @lan_id,
 'Mình chỉ tổng hợp lại link công khai từ giảng viên, không phải nội dung trùng lặp hoàn toàn với bài đã ghim.',
 'rejected', @admin_id,
 'Nội dung vẫn trùng lặp phần lớn với tài nguyên đã ghim, cần bổ sung góc nhìn riêng trước khi đăng lại.',
 CURRENT_TIMESTAMP - INTERVAL 3 DAY, CURRENT_TIMESTAMP - INTERVAL 2 DAY);

-- Moderation queue and audit history.
INSERT INTO reports (
    reporter_id, post_id, comment_id, handled_by, reason, details,
    status, resolution_note, created_at, handled_at
) VALUES
(@an_id, @p2, NULL, NULL, 'misinformation', 'Một số số liệu chi phí cần nguồn tham khảo.',
 'pending', NULL, CURRENT_TIMESTAMP - INTERVAL 1 DAY, NULL),
(@lan_id, NULL, @p1_first_comment, @mod_id, 'other', 'Báo cáo thử nghiệm quy trình kiểm duyệt.',
 'resolved', 'Nội dung không vi phạm, giữ nguyên bình luận.', CURRENT_TIMESTAMP - INTERVAL 8 DAY, CURRENT_TIMESTAMP - INTERVAL 7 DAY);

INSERT INTO moderation_logs (
    moderator_id, target_user_id, post_id, comment_id, action, reason, created_at
) VALUES
(@admin_id, @spammer_id, NULL, NULL, 'ban_user', 'Đăng nội dung quảng cáo lặp lại.', CURRENT_TIMESTAMP - INTERVAL 5 DAY),
(@mod_id, NULL, @p2, NULL, 'pin_post', 'Bài thảo luận có giá trị tham khảo cao.', CURRENT_TIMESTAMP - INTERVAL 4 DAY),
(@mod_id, NULL, @p9, NULL, 'pin_post', 'Hướng dẫn thiết lập dự án dành cho thành viên mới.', CURRENT_TIMESTAMP - INTERVAL 2 DAY),
(@mod_id, NULL, NULL, @p1_first_comment, 'resolve_report', 'Đã xem xét, bình luận không vi phạm.', CURRENT_TIMESTAMP - INTERVAL 7 DAY),
(@mod_id, @phuc_id, @p_hidden1, NULL, 'hide_post', 'Bài viết chứa liên kết tải xuống chưa được kiểm chứng, có nguy cơ vi phạm bản quyền.', CURRENT_TIMESTAMP - INTERVAL 4 DAY),
(@admin_id, @lan_id, @p_hidden2, NULL, 'hide_post', 'Nội dung trùng lặp với tài nguyên đã được BQT ghim trước đó.', CURRENT_TIMESTAMP - INTERVAL 6 DAY),
(@admin_id, @lan_id, @p_hidden2, NULL, 'reject_appeal', 'Nội dung vẫn trùng lặp phần lớn với tài nguyên đã ghim, cần bổ sung góc nhìn riêng trước khi đăng lại.', CURRENT_TIMESTAMP - INTERVAL 2 DAY);

COMMIT;
